::print("Nortel 1  \n")
::print("CALLER_NUMBER="+ Record.CALLER_NUMBER )
::print("\n")
::print("CALLED_NUMBER="+ Record.CALLED_NUMBER )
::print("\n")
::print("TIME="+ Record.TIME )
::print("\n")
::print("DURATION="+ Record.DURATION )
::print("\n")
::print("CALLER_IMEI="+ Record.CALLER_IMEI )
::print("\n")
::print("CALLED_IMEI="+ Record.CALLED_IMEI )
::print("\n")
::print("CALLER_MSC="+ Record.CALLER_MSC )
::print("\n")
::print("CALLED_msc="+ Record.CALLED_msc )
::print("\n")
